title:             Heesang Blog
email:             khsiea@gmail.com
description:       작은 개발 삽질 정리 블로그
author:            khsiea
baseurl:           "/"
url:               "http://khsiea.github.io"

# Social Profiles
twitter_username:  khsiea1
github_username:   khsiea
facebook_username: khsiea

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
